Repository projectsyn/component-cilium, pull requests merged in 2022-11, with the labels that each got.

#63 Create aggregated clusterroles for `cilium.io` resources
  class/cilium.yml
  component/aggregated-clusterroles.jsonnet
  docs/modules/ROOT/pages/index.adoc
  tests/golden/defaults/cilium/cilium/02_aggregated_clusterroles.yaml
  tests/golden/helm-opensource/cilium/cilium/02_aggregated_clusterroles.yaml
  tests/golden/olm-opensource/cilium/cilium/02_aggregated_clusterroles.yaml
Labels: enhancement

#64 Switch component class to use `${_base_directory}`
  class/cilium.yml
Labels: change

#49 Update dependency docker.io/bitnami/kubectl to v1.25.3
  class/defaults.yml
  tests/golden/olm-opensource/cilium/cilium/olm/99_cleanup.yaml
Labels: dependency

#46 Update docker.io/bitnami/kubectl digest to 1841cb1
  class/defaults.yml
  tests/golden/olm-opensource/cilium/cilium/olm/99_cleanup.yaml
Labels: dependency

#67 Update dependency docker.io/bitnami/kubectl to v1.25.4
  class/defaults.yml
  tests/golden/olm-opensource/cilium/cilium/olm/99_cleanup.yaml
Labels: dependency

#68 Update docker.io/bitnami/kubectl digest to 92441ac
  class/defaults.yml
  tests/golden/olm-opensource/cilium/cilium/olm/99_cleanup.yaml
Labels: dependency
