Repository projectsyn/component-cilium, pull requests merged in 2022-06, with the labels that each got.

#39 Update `.sync.yml` for latest modulesync template
  .sync.yml
Labels: ignore

#41 Add guide to upgrade Cilium to enterprise on OCP4
  docs/modules/ROOT/pages/how-tos/openshift4/upgrade-cilium-oss-to-cilium-enterprise.adoc
  docs/modules/ROOT/pages/references/parameters.adoc
  docs/modules/ROOT/partials/nav.adoc
Labels: documentation

#47 Update dependency docker.io/bitnami/kubectl to v1.24.2
  class/defaults.yml
  tests/golden/olm-opensource/cilium/cilium/olm/99_cleanup.yaml
Labels: dependency
