Repository projectsyn/component-cilium, pull requests merged in 2024-04, with the labels that each got.

#103 Add support for configuring OLM operator log level
  class/defaults.yml
  component/olm.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/olm-opensource/cilium/cilium/olm/cluster-network-06-cilium-00002-cilium-olm-deployment.yaml
  tests/golden/olm-opensource/cilium/cilium/olm/cluster-network-06-cilium-00014-cilium.v1.13.8-xe0355c7-clusterserviceversion.yaml
Labels: enhancement

#105 Enable Hubble Relay by default
  class/defaults.yml
  tests/golden/defaults/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble-relay/configmap.yaml
  tests/golden/defaults/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble-relay/deployment.yaml
  tests/golden/defaults/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble-relay/service.yaml
  tests/golden/defaults/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble-relay/serviceaccount.yaml
  tests/golden/egress-gateway/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble-relay/configmap.yaml
  tests/golden/egress-gateway/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble-relay/deployment.yaml
  tests/golden/egress-gateway/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble-relay/service.yaml
  tests/golden/egress-gateway/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble-relay/serviceaccount.yaml
  tests/golden/helm-opensource/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble-relay/configmap.yaml
  tests/golden/helm-opensource/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble-relay/deployment.yaml
  tests/golden/helm-opensource/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble-relay/service.yaml
  tests/golden/helm-opensource/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble-relay/serviceaccount.yaml
  tests/golden/olm-opensource/cilium/cilium/olm/cluster-network-07-cilium-ciliumconfig.yaml
Labels: enhancement

#98 Update docker.io/bitnami/kubectl Docker tag to v1.29.4
  class/defaults.yml
  tests/golden/olm-opensource/cilium/cilium/olm/99_cleanup.yaml
Labels: dependency

#106 Add support for deploying a configmap holding egress IP shadow ranges
  class/defaults.yml
  component/egress-gateway-policies.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/egress-gateway.yml
  tests/golden/egress-gateway/cilium/cilium/20_namespace_egress_ip_policies.yaml
  tests/golden/egress-gateway/cilium/cilium/30_egress_ip_shadow_ranges.yaml
Labels: enhancement

#108 Pre-render Helm values in Jsonnet
  class/cilium.yml
  class/defaults.yml
  component/olm.jsonnet
  component/render-helm-values.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/olm-opensource/cilium/cilium/olm/cluster-network-07-cilium-ciliumconfig.yaml
Labels: change

#110 Prepare migration to `IsovalentEgressGatewayPolicy` resources
  component/aggregated-clusterroles.jsonnet
  component/egress-gateway-policies.jsonnet
  tests/golden/defaults/cilium/cilium/02_aggregated_clusterroles.yaml
  tests/golden/egress-gateway/cilium/cilium/02_aggregated_clusterroles.yaml
  tests/golden/egress-gateway/cilium/cilium/20_egress_gateway_policies.yaml
  tests/golden/egress-gateway/cilium/cilium/20_namespace_egress_ip_policies.yaml
  tests/golden/helm-opensource/cilium/cilium/02_aggregated_clusterroles.yaml
  tests/golden/olm-opensource/cilium/cilium/02_aggregated_clusterroles.yaml
Labels: change
