Repository projectsyn/component-cilium, pull requests merged in 2024-08, with the labels that each got.

#131 Update docker.io/bitnami/kubectl Docker tag to v1.30.4
  class/defaults.yml
  tests/golden/egress-gateway/cilium/cilium/30_egress_ip_shadow_ranges.yaml
  tests/golden/l2-announcement/cilium/cilium/01_cilium_helmchart/00_cilium_namespace.yaml
  tests/golden/l2-announcement/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/clusterrole.yaml
  tests/golden/l2-announcement/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/clusterrolebinding.yaml
  tests/golden/l2-announcement/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/daemonset.yaml
  tests/golden/l2-announcement/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/role.yaml
  tests/golden/l2-announcement/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/rolebinding.yaml
  tests/golden/l2-announcement/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/service.yaml
  tests/golden/l2-announcement/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/serviceaccount.yaml
  tests/golden/l2-announcement/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/servicemonitor.yaml
  tests/golden/l2-announcement/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml
  tests/golden/l2-announcement/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-operator/clusterrole.yaml
  tests/golden/l2-announcement/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-operator/clusterrolebinding.yaml
  tests/golden/l2-announcement/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-operator/deployment.yaml
  tests/golden/l2-announcement/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-operator/serviceaccount.yaml
  tests/golden/l2-announcement/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble-relay/configmap.yaml
  tests/golden/l2-announcement/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble-relay/deployment.yaml
  tests/golden/l2-announcement/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble-relay/service.yaml
  tests/golden/l2-announcement/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble-relay/serviceaccount.yaml
  tests/golden/l2-announcement/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble/metrics-service.yaml
  tests/golden/l2-announcement/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble/peer-service.yaml
  tests/golden/l2-announcement/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble/servicemonitor.yaml
  tests/golden/l2-announcement/cilium/cilium/02_aggregated_clusterroles.yaml
  tests/golden/olm-opensource/cilium/cilium/olm/99_cleanup.yaml
Labels: dependency, automerge, bump:patch

#129 Support deploying CiliumL2AnnouncementPolicies
  class/cilium.yml
  class/defaults.yml
  component/l2-announcement-policies.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml
  tests/golden/defaults/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml
  tests/golden/egress-gateway/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml
  tests/golden/helm-opensource/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml
  tests/golden/l2-announcement/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/clusterrole.yaml
  tests/golden/l2-announcement/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml
  tests/golden/l2-announcement/cilium/cilium/40_l2_announcement_policies.yaml
  tests/golden/olm-opensource/cilium/cilium/olm/cluster-network-07-cilium-ciliumconfig.yaml
  tests/l2-announcement.yml
Labels: enhancement, bump:minor

#132 Update docker.io/bitnami/kubectl:1.30.4 Docker digest to 68a21ff
  class/defaults.yml
  tests/golden/egress-gateway/cilium/cilium/30_egress_ip_shadow_ranges.yaml
  tests/golden/olm-opensource/cilium/cilium/olm/99_cleanup.yaml
Labels: dependency, automerge, bump:patch

#133 Change naming of L2 Announcements manifests
  component/l2-announcement-policies.jsonnet
  tests/golden/l2-announcement/cilium/cilium/50_l2_announcement_policies.yaml
Labels: change

#134 Allow creating CiliumLoadBalancerIPPool with L2 Announcements
  class/defaults.yml
  component/bgp-control-plane.jsonnet
  component/l2-announcement-policies.jsonnet
  component/olm.jsonnet
  component/util.libsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/l2-announcement/cilium/cilium/50_loadbalancer_ip_pools.yaml
  tests/l2-announcement.yml
Labels: change, bump:patch

#136 Update docker.io/bitnami/kubectl:1.30.4 Docker digest to 4f74249
  class/defaults.yml
  tests/golden/egress-gateway/cilium/cilium/30_egress_ip_shadow_ranges.yaml
  tests/golden/olm-opensource/cilium/cilium/olm/99_cleanup.yaml
Labels: dependency, automerge, bump:patch
