Repository projectsyn/component-cilium, pull requests merged in 2024-07, with the labels that each got.

#118 Add support for configuring the BGP control plane
  .cruft.json
  .github/workflows/test.yaml
  Makefile.vars.mk
  class/cilium.yml
  class/defaults.yml
  component/bgp-control-plane.jsonnet
  component/olm.jsonnet
  component/util.libsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/bgp-control-plane.yml
  tests/golden/bgp-control-plane/cilium/apps/cilium.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/00_cilium_namespace.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/clusterrole.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/clusterrolebinding.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/daemonset.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/role.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/rolebinding.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/service.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/serviceaccount.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/servicemonitor.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-operator/clusterrole.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-operator/clusterrolebinding.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-operator/deployment.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-operator/serviceaccount.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-secrets-namespace.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble-relay/configmap.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble-relay/deployment.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble-relay/service.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble-relay/serviceaccount.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble/peer-service.yaml
  tests/golden/bgp-control-plane/cilium/cilium/02_aggregated_clusterroles.yaml
  tests/golden/bgp-control-plane/cilium/cilium/40_bgp_peerings.yaml
  tests/golden/bgp-control-plane/cilium/cilium/40_loadbalancer_ip_pools.yaml
  tests/golden/olm-opensource/cilium/cilium/olm/cluster-network-07-cilium-ciliumconfig.yaml
Labels: enhancement

#119 Manage OpenShift's kube-proxy deployment based on the value of `kubeProxyReplacement`
  .cruft.json
  .github/workflows/test.yaml
  Makefile.vars.mk
  class/cilium.yml
  component/helm-namespace.jsonnet
  component/ocp-manage-kube-proxy.jsonnet
  component/util.libsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/kubeproxyreplacement-strict/cilium/apps/cilium.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/00_cilium_namespace.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/clusterrole.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/clusterrolebinding.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/daemonset.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/role.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/rolebinding.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/service.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/serviceaccount.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/servicemonitor.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-operator/clusterrole.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-operator/clusterrolebinding.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-operator/deployment.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-operator/serviceaccount.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-secrets-namespace.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble-relay/configmap.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble-relay/deployment.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble-relay/service.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble-relay/serviceaccount.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble/peer-service.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/02_aggregated_clusterroles.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/99_networkoperator_kube_proxy_patch.yaml
  tests/helm-enterprise-openshift.yml
  tests/helm-enterprise.yml
  tests/kubeproxyreplacement-strict.yml
Labels: enhancement

#120 Update component defaults to set `kubeProxyReplacement="true"`
  class/defaults.yml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml
  tests/golden/defaults/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml
  tests/golden/egress-gateway/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml
  tests/golden/helm-opensource/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml
  tests/golden/olm-opensource/cilium/cilium/olm/cluster-network-07-cilium-ciliumconfig.yaml
Labels: change

#84 Update Helm release cilium to v1.15.6
  class/cilium.yml
  class/defaults.yml
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/clusterrole.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/daemonset.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/role.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/rolebinding.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/servicemonitor.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-operator/clusterrole.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-operator/deployment.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-secrets-namespace.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble-relay/deployment.yaml
  tests/golden/bgp-control-plane/cilium/cilium/40_loadbalancer_ip_pools.yaml
  tests/golden/defaults/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/clusterrole.yaml
  tests/golden/defaults/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/daemonset.yaml
  tests/golden/defaults/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/servicemonitor.yaml
  tests/golden/defaults/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml
  tests/golden/defaults/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-operator/clusterrole.yaml
  tests/golden/defaults/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-operator/deployment.yaml
  tests/golden/defaults/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-secrets-namespace.yaml
  tests/golden/defaults/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble-relay/deployment.yaml
  tests/golden/egress-gateway/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/clusterrole.yaml
  tests/golden/egress-gateway/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/daemonset.yaml
  tests/golden/egress-gateway/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/servicemonitor.yaml
  tests/golden/egress-gateway/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml
  tests/golden/egress-gateway/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-operator/clusterrole.yaml
  tests/golden/egress-gateway/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-operator/deployment.yaml
  tests/golden/egress-gateway/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-secrets-namespace.yaml
  tests/golden/egress-gateway/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble-relay/deployment.yaml
  tests/golden/helm-opensource/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/clusterrole.yaml
  tests/golden/helm-opensource/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/daemonset.yaml
  tests/golden/helm-opensource/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/servicemonitor.yaml
  tests/golden/helm-opensource/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml
  tests/golden/helm-opensource/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-operator/clusterrole.yaml
  tests/golden/helm-opensource/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-operator/deployment.yaml
  tests/golden/helm-opensource/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-secrets-namespace.yaml
  tests/golden/helm-opensource/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble-relay/deployment.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/clusterrole.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/daemonset.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/servicemonitor.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-operator/clusterrole.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-operator/deployment.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-secrets-namespace.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble-relay/deployment.yaml
Labels: dependency

#112 Update docker.io/bitnami/kubectl Docker tag to v1.30.2
  class/defaults.yml
  tests/golden/egress-gateway/cilium/cilium/30_egress_ip_shadow_ranges.yaml
  tests/golden/olm-opensource/cilium/cilium/olm/99_cleanup.yaml
Labels: dependency

#121 Update Cilium EE default Helm chart version to 1.15.6
  class/defaults.yml
Labels: dependency

#122 Enable BPF masquerading by default
  class/defaults.yml
  component/render-helm-values.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml
  tests/golden/defaults/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml
  tests/golden/helm-opensource/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml
  tests/golden/olm-opensource/cilium/cilium/olm/cluster-network-07-cilium-ciliumconfig.yaml
Labels: change

#123 Enable some hubble metrics by default
  class/defaults.yml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/daemonset.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble/metrics-service.yaml
  tests/golden/bgp-control-plane/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble/servicemonitor.yaml
  tests/golden/defaults/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/daemonset.yaml
  tests/golden/defaults/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml
  tests/golden/defaults/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble/metrics-service.yaml
  tests/golden/defaults/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble/servicemonitor.yaml
  tests/golden/egress-gateway/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/daemonset.yaml
  tests/golden/egress-gateway/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml
  tests/golden/egress-gateway/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble/metrics-service.yaml
  tests/golden/egress-gateway/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble/servicemonitor.yaml
  tests/golden/helm-opensource/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/daemonset.yaml
  tests/golden/helm-opensource/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml
  tests/golden/helm-opensource/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble/metrics-service.yaml
  tests/golden/helm-opensource/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble/servicemonitor.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-agent/daemonset.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/cilium-configmap.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble/metrics-service.yaml
  tests/golden/kubeproxyreplacement-strict/cilium/cilium/01_cilium_helmchart/cilium/templates/hubble/servicemonitor.yaml
  tests/golden/olm-opensource/cilium/cilium/olm/cluster-network-07-cilium-ciliumconfig.yaml
Labels: enhancement

#124 Update docker.io/bitnami/kubectl Docker tag to v1.30.3
  class/defaults.yml
  tests/golden/egress-gateway/cilium/cilium/30_egress_ip_shadow_ranges.yaml
  tests/golden/olm-opensource/cilium/cilium/olm/99_cleanup.yaml
Labels: dependency, automerge, bump:patch
